# Generated by Django 5.2.16 on 2026-07-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_categriy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategories/'),
        ),
    ]
